### ISSUE TITLE
Mod not working with fabric 1.12.3 server

### ISSUE THREAD

**Issue by le0flo** [zly2006/x-backup#2]
- Mod version: `0.2.4`
- Jvm: `adoptium jdk 21`
- Other mods present:
  - `fabric-api-0.110.0+1.21.3.jar`
  - `ferritecore-7.1.0-hotfix-fabric.jar`
  - `lithium-fabric-0.14.2-snapshot+mc1.21.3-build.91.jar`
  - `voicechat-fabric-1.21.3-2.5.26.jar`
  - `fabric-language-kotlin-1.13.0+kotlin.2.1.0.jar`
  - `geyser-fabric-Geyser-Fabric-2.5.0-b719.jar`
  - `spark-1.10.119-fabric.jar`
  - `x-backup-0.2.4.jar`

Error log:
```
[18:18:41] [main/ERROR]: Error loading language
java.lang.NullPointerException: null
        at knot/com.github.zly2006.xbackup.mc121_2.Impl.reloadLanguage(Impl.kt:30) ~[x_backup_1_21_3-0.2.4+1_21_3-3b6746ffdba09363.jar:?]
        at knot/com.github.zly2006.xbackup.XBackup.loadConfig(XBackup.kt:56) ~[x_backup_core-0.2.3-6c61124f87560dbb.jar:?]
        at knot/com.github.zly2006.xbackup.XBackup.onInitialize(XBackup.kt:83) ~[x_backup_core-0.2.3-6c61124f87560dbb.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) [fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
[18:18:41] [main/ERROR]: Error loading default language
java.lang.NullPointerException: null
        at knot/com.github.zly2006.xbackup.mc121_2.Impl.reloadLanguage(Impl.kt:30) ~[x_backup_1_21_3-0.2.4+1_21_3-3b6746ffdba09363.jar:?]
        at knot/com.github.zly2006.xbackup.XBackup.loadConfig(XBackup.kt:60) ~[x_backup_core-0.2.3-6c61124f87560dbb.jar:?]
        at knot/com.github.zly2006.xbackup.XBackup.onInitialize(XBackup.kt:83) ~[x_backup_core-0.2.3-6c61124f87560dbb.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) [fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
[18:18:41] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:18:44] [main/INFO]: Loaded 1337 recipes
[18:18:44] [main/INFO]: Loaded 1448 advancements
[18:18:44] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 3.050 ms
[18:18:44] [Server thread/INFO]: Starting background profiler...
[18:18:45] [Server thread/INFO]: Starting minecraft server version 1.21.3
[18:18:45] [Server thread/INFO]: Loading properties
[18:18:45] [Server thread/INFO]: Default game type: SURVIVAL
[18:18:45] [Server thread/INFO]: Generating keypair
[18:18:45] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:18:45] [Server thread/INFO]: Using epoll channel type
[18:18:45] [Server thread/INFO]: Preparing level "world"
[18:18:46] [Server thread/ERROR]: Mixin apply for mod x_backup_1_21_3 failed x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3 -> net.minecraft.class_4698: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3->@Inject::run(Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/class_4698$class_10195;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT_APPLY Applicator Phase -> x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3 -> Apply Injections ->  -> Inject -> x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3->@Inject::run(Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3->@Inject::run(Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/class_4698$class_10195;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT_APPLY Applicator Phase -> x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3 -> Apply Injections ->  -> Inject -> x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3->@Inject::run(Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
        at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:560) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:490) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:284) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:508) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1483) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_9172.<init>(class_9172.java:25) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3218.<init>(class_3218.java:242) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:391) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:356) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3176.method_3823(class_3176.java:184) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:678) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[18:18:46] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4698 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/net.minecraft.class_9172.<init>(class_9172.java:25) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3218.<init>(class_3218.java:242) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:391) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:356) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3176.method_3823(class_3176.java:184) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:678) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        ... 12 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3] from phase [DEFAULT] in config [x_backup.121.2.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        ... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3->@Inject::run(Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V! Expected (Lnet/minecraft/class_4698$class_10195;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V [INJECT_APPLY Applicator Phase -> x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3 -> Apply Injections ->  -> Inject -> x_backup.121.2.mixins.json:MixinStorageIoWorker from mod x_backup_1_21_3->@Inject::run(Ljava/util/function/Supplier;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V]
        at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:560) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:490) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:284) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:508) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1483) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        ... 12 more
[18:18:46] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/vanilla/crash-reports/crash-2024-11-30_18.18.46-server.txt
[18:18:46] [Server thread/INFO]: Geyser shutdown successfully.
[18:18:46] [Server thread/INFO]: Stopping server
[18:18:46] [Server thread/INFO]: Saving players
[18:18:46] [Server thread/INFO]: Saving worlds
[18:18:46] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
        at knot/net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:575) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:634) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3176.method_3782(class_3176.java:543) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:754) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Btw, when trying to get the latest version for 1.21.3, which on the modrinth website is set to 0.2.3, the site downloads the 0.2.4.

**Comment by zly2006** [comment]
I uploaded 0.2.8 versions on modrinth, please help test it.

**Comment by le0flo** [comment]
Now it works perfectly. Thanks.
