### ISSUE TITLE
Can't Prune backups

### ISSUE THREAD

**Issue by zaBees** [zly2006/x-backup#5]
```
Fabric 1.20.1 - 1.16.5
Mod x-backup-0.3.5+1.20.1.jar
```

I ran "xb prune" in the console, but nothing seems to happen and when i check the backups are all still there.

> {
>     "ignored_files": [
>         "session.lock",
>         "fake_player.gca.json",
>         "ledger.sqlite"
>     ],
>     "blob_path": "blob",
>     "backup_interval": 10800,
>     "backup_before_restore": true,
>     "mirror_mode": false,
>     "mirror_from": null,
>     "language": "en_us",
>     "prune": {
>         "enabled": true,
>         "keep_policy": {
>             "1d": "30m"
>         },
>         "keep_temporary": "6h"
>     },
>     "cloud_backup_token": null
> }
that's my config and there's nothin in the logs

**Comment by zly2006** [comment]
Please send a list of all backups. you can use `/xb list` to view all backups and send the log

**Comment by zaBees** [comment]
a I've cleaned them manually I'll let u know once they build up again

**Comment by zaBees** [comment]
> ubuntu@minecraft-server:~/Prominence$ ./start.sh
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.ranged_damage' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:converttofire' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:converttoarcane' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.fortune' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:warding' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.jump' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:magic_protection' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:bonus_loot_count_rolls' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:lung_capacity' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.resistance' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:converttofrost' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:dig_speed' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:convertfromfrost' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:water_visibility' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'minecraft:estrogen.boob_initial_size' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.stamina' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:critical_bonus_damage' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.healing' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:convertfromarcane' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:convertfromfire' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.sprinting_speed' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.knockback' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:dropped_experience' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.melee_damage' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'minecraft:estrogen.boob_growing_start_time' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'spellbladenext:converttoheal' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:lava_visibility' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'puffish_skills:player.mining_speed' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:water_speed' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'minecraft:estrogen.dash_level' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:lava_speed' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'additionalentityattributes:bonus_rare_loot_rolls' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/ERROR]: Attribute ID 'minecraft:estrogen.current_dashes' does not belong to a known attribute. This entry will be ignored.
> [18:34:54] [Server thread/INFO]: Loaded 166 values from config.
> [18:34:54] [Server thread/INFO]: Saving config file. 166 entries.
> [18:34:54] [Server thread/INFO]: Applying changes for 166 attributes.
> [18:34:54] [Server thread/INFO]: Loading claims...
> [18:34:54] [Server thread/INFO]: Loaded claims in 25ms
> [18:34:54] [Server thread/WARN]: The configured permission system "prometheus" isn't registered!
> [18:34:54] [Server thread/INFO]: Configured OPAC to use the following permission system: luck_perms
> [18:34:54] [Server thread/WARN]: The configured primary party system "argonauts_guilds" isn't registered!
> [18:34:54] [Server thread/INFO]: Configured OPAC to use the following party system as primary: default
> [18:34:54] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2149ms or 42 ticks behind
> [18:34:57] [Server thread/ERROR]: Uncaught exception in server thread
> kotlin.UninitializedPropertyAccessException: lateinit property oneDriveService has not been initialized
>         at com.github.zly2006.xbackup.BackupDatabaseService.getCloudStorageProvider(BackupDatabaseService.kt:80) ~[x-backup-0.3.5+1.20.1.jar:?]
>         at com.github.zly2006.xbackup.XBackup$onInitialize$4$2.invokeSuspend(XBackup.kt:221) ~[x-backup-0.3.5+1.20.1.jar:?]
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-2.0.10-7058370f10f21d1.jar:?]
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
>         at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
>         at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[server-intermediary.jar:?]
>         at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]
>         at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:764) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
>         at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:742) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.handler$cki000$carpet$modifiedRunLoop(MinecraftServer.java:22451) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650) ~[server-intermediary.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
>         at java.lang.Thread.run(Thread.java:1583) ~[?:?]
>         Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException
> [18:34:58] [Server thread/INFO]: [STDOUT]: Finalizing fluid block registration
> [18:34:58] [Server thread/INFO]: [STDOUT]: Finalizing fluid item registration
> [18:34:59] [Server thread/ERROR]: Failed to handle entity type entity.dummmmmmy.target_dummy
> [18:34:59] [Server thread/ERROR]: Failed to handle entity type entity.dummmmmmy.target_dummy
> [18:34:59] [Server thread/ERROR]: Failed to handle entity type entity.dummmmmmy.target_dummy
> [18:34:59] [Server thread/ERROR]: Failed to handle entity type entity.dummmmmmy.target_dummy
> [18:34:59] [Server thread/WARN]: @Redirect conflict. Skipping redirector.mixins.json:net.minecraft.world.level.block.piston.PistonStructureResolverMixin from mod redirector->@Redirect::redirectDirections()[Lnet/minecraft/class_2350; with priority 10, already redirected by lithium.mixins.json:alloc.enum_values.piston_handler.PistonHandlerMixin from mod lithium->@Redirect::removeAllocation()[Lnet/minecraft/class_2350; with priority 1000
> [18:35:00] [Server thread/INFO]: [STDOUT]: Finalizing energy block registration
> [18:35:05] [DefaultDispatcher-worker-2/INFO]: Running scheduled backup, please wait...
> [18:35:10] [DefaultDispatcher-worker-65/INFO]: [X Backup] Backed up 3321 files, 79 new, 3242 files reused
> [18:35:11] [DefaultDispatcher-worker-12/INFO]: Scheduled backup #84 finished, 1.2 GB (740.2 MB after compression) +170.0 MB in 5999 ms
> [18:35:15] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5763ms or 115 ticks behind
> xb prune
> xb list
> [18:35:47] [Server thread/INFO]: Backups:
> [18:35:47] [Server thread/INFO]:   #84 Scheduled backup (1.2 GB) on 18:35
> [18:35:47] [Server thread/INFO]:   #60 dragon? by gay_ikea_table (2.6 GB) on 12-21 17:15
> [18:35:47] [Server thread/INFO]:   #59 Scheduled backup (2.5 GB) on 12-21 15:05
> [18:35:47] [Server thread/INFO]:   #58 Scheduled backup (2.5 GB) on 12-21 12:05
> [18:35:47] [Server thread/INFO]:   #57 Scheduled backup (2.5 GB) on 12-21 09:05
> [18:35:47] [Server thread/INFO]:   #56 Scheduled backup (2.5 GB) on 12-21 06:05
> [18:35:47] [Server thread/INFO]: More backups...
> 

I've changed my config to 15h with 3h
It works when I have 2 lines in for example:
"15h": "3h",
"1w": "1d"
but when I delete the bottom line it stops working

**Comment by handsome-steve** [comment]
Thankyou for this <3 helped me out

**Comment by zly2006** [comment]
Hi

> I've changed my config to 15h with 3h
> It works when I have 2 lines in for example:
> "15h": "3h",
> "1w": "1d"

This is how it works: if that backup is less than 15 hours to now, xb keeps one backup per 3h. However, the "1w" in fact means nothing -- if a backup is create more than a week ago, xb still keeps 1 backup per day, thats why when you delete this line, it prunes nothing.

Also there is another setting that dont prune backups in two days, to avoid accidentally deleting backups.

**Comment by icewolf-li** [comment]
说起来我没有读懂这个配置的说明，我思考了很久，但是我不理解什么是“保留最近1天内每30分钟的备份”，指的是保留一天的每隔30分钟的备份吗？
我是用的默认的3小时自动备份，但是我想超过5个的部分自动删除，也就是说目前有六个备份的时候删除距离现在最远的那一个，应该怎么编写配置文件
"keep_temporary": "1d"
这个是什么作用的，翻译过来是“保持临时状态”，我没理解是什么
但有一说一，这个相比其他的备份mod，在1.21.4确实好用

**Comment by zly2006** [comment]
> 说起来我没有读懂这个配置的说明，我思考了很久，但是我不理解什么是“保留最近1天内每30分钟的备份”，指的是保留一天的每隔30分钟的备份吗？ 我是用的默认的3小时自动备份，但是我想超过5个的部分自动删除，也就是说目前有六个备份的时候删除距离现在最远的那一个，应该怎么编写配置文件 "keep_temporary": "1d" 这个是什么作用的，翻译过来是“保持临时状态”，我没理解是什么 但有一说一，这个相比其他的备份mod，在1.21.4确实好用

keep_temporary：在此时间内的备份永远不会进行删除
> 我是用的默认的3小时自动备份，但是我想超过5个的部分自动删除，也就是说目前有六个备份的时候删除距离现在最远的那一个

删除会留下最远的存档，并逐渐向现在的方向删除，所以必然有一个存档满足不了你的要求。你可以"1y":"15h"并把keep_temporary改成15h
